# Data Visualization - Episodes Ranking for "Game of Thrones"

https://datascientyst.com/dataisbeautiful-the-absolute-quality-of-breaking-bad/

## Step 1: Get to IMDB and choose TV series

### Get the identifier by selecting only the last numbers from the url. For example from https://www.imdb.com/title/tt0944947/ get 0944947

## Step 2: Scrape IMDb movie data

### Install sinemagoer

In [1]:
pip install cinemagoer

Requirement already satisfied: cinemagoer in /home/desi/PycharmProjects/Pandas-Exercises-Projects/venv/lib/python3.11/site-packages (2022.2.11)
Requirement already satisfied: SQLAlchemy in /home/desi/PycharmProjects/Pandas-Exercises-Projects/venv/lib/python3.11/site-packages (from cinemagoer) (1.4.43)
Requirement already satisfied: lxml in /home/desi/PycharmProjects/Pandas-Exercises-Projects/venv/lib/python3.11/site-packages (from cinemagoer) (4.9.1)
Requirement already satisfied: greenlet!=0.4.17 in /home/desi/PycharmProjects/Pandas-Exercises-Projects/venv/lib/python3.11/site-packages (from SQLAlchemy->cinemagoer) (2.0.1)
WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.
You should consider upgrading via the '/home/desi/PycharmProjects/Pandas-Exercises-Projects/venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

### Get IMDb movie info

In [2]:
from imdb import Cinemagoer

# create an instance of the Cinemagoer class
cg = Cinemagoer()

In [3]:
# get a movie and print its director(s)
avatar = cg.get_movie('0499549')
for director in avatar['directors']:
    print(director['name'])

James Cameron

### Search for movies by title

In [4]:
# movies = cg.search_movie('Game of Thrones')
# movies

### Extract IMDb series

In [5]:
# get information for "Game of Thrones"
series = cg.get_movie('0944947')
series

In [6]:
# series['episodes']

In [7]:
cg.update(series, 'episodes')
seasons_info = series['episodes']
seasons_info

{1: {1: <Movie id:1480055[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Winter Is Coming (2011)_>,
  2: <Movie id:1668746[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Kingsroad (2011)_>,
  3: <Movie id:1829962[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Lord Snow (2011)_>,
  4: <Movie id:1829963[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Cripples, Bastards, and Broken Things (2011)_>,
  5: <Movie id:1829964[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Wolf and the Lion (2011)_>,
  6: <Movie id:1837862[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" A Golden Crown (2011)_>,
  7: <Movie id:1837863[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" You Win or You Die (2011)_>,
  8: <Movie id:1837864[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Pointy End (2011)_>,
  9: <Movie id:1851398[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Baelor (2011)_>,
  10: <Movie id:1851397[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Fire and Blood (2011)_>},
 2: {1: <Movie id:1971833[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The North Remembers (2012)_>,
  2: <Movie id:2069318[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Night Lands (2012)_>,
  3: <Movie id:2070135[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" What Is Dead May Never Die (2012)_>,
  4: <Movie id:2069319[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Garden of Bones (2012)_>,
  5: <Movie id:2074658[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Ghost of Harrenhal (2012)_>,
  6: <Movie id:2085238[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Old Gods and the New (2012)_>,
  7: <Movie id:2085239[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" A Man Without Honor (2012)_>,
  8: <Movie id:2085240[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Prince of Winterfell (2012)_>,
  9: <Movie id:2084342[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Blackwater (2012)_>,
  10: <Movie id:2112510[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Valar Morghulis (2012)_>},
 3: {1: <Movie id:2178782[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Valar Dohaeris (2013)_>,
  2: <Movie id:2178772[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Dark Wings, Dark Words (2013)_>,
  3: <Movie id:2178802[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Walk of Punishment (2013)_>,
  4: <Movie id:2178798[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" And Now His Watch Is Ended (2013)_>,
  5: <Movie id:2178788[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Kissed by Fire (2013)_>,
  6: <Movie id:2178812[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Climb (2013)_>,
  7: <Movie id:2178814[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Bear and the Maiden Fair (2013)_>,
  8: <Movie id:2178806[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Second Sons (2013)_>,
  9: <Movie id:2178784[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Rains of Castamere (2013)_>,
  10: <Movie id:2178796[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Mhysa (2013)_>},
 4: {1: <Movie id:2816136[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Two Swords (2014)_>,
  2: <Movie id:2832378[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Lion and the Rose (2014)_>,
  3: <Movie id:2972426[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Breaker of Chains (2014)_>,
  4: <Movie id:2972428[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Oathkeeper (2014)_>,
  5: <Movie id:3060856[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" First of His Name (2014)_>,
  6: <Movie id:3060910[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Laws of Gods and Men (2014)_>,
  7: <Movie id:3060876[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Mockingbird (2014)_>,
  8: <Movie id:3060782[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Mountain and the Viper (2014)_>,
  9: <Movie id:3060858[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Watchers on the Wall (2014)_>,
  10: <Movie id:3060860[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Children (2014)_>},
 5: {1: <Movie id:3658012[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Wars to Come (2015)_>,
  2: <Movie id:3846626[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The House of Black and White (2015)_>,
  3: <Movie id:3866836[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" High Sparrow (2015)_>,
  4: <Movie id:3866838[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Sons of the Harpy (2015)_>,
  5: <Movie id:3866840[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Kill the Boy (2015)_>,
  6: <Movie id:3866842[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Unbowed, Unbent, Unbroken (2015)_>,
  7: <Movie id:3866846[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Gift (2015)_>,
  8: <Movie id:3866850[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Hardhome (2015)_>,
  9: <Movie id:3866826[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Dance of Dragons (2015)_>,
  10: <Movie id:3866862[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Mother's Mercy (2015)_>},
 6: {1: <Movie id:3658014[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Red Woman (2016)_>,
  2: <Movie id:4077554[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Home (2016)_>,
  3: <Movie id:4131606[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Oathbreaker (2016)_>,
  4: <Movie id:4283016[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Book of the Stranger (2016)_>,
  5: <Movie id:4283028[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Door (2016)_>,
  6: <Movie id:4283054[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Blood of My Blood (2016)_>,
  7: <Movie id:4283060[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Broken Man (2016)_>,
  8: <Movie id:4283074[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" No One (2016)_>,
  9: <Movie id:4283088[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Battle of the Bastards (2016)_>,
  10: <Movie id:4283094[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Winds of Winter (2016)_>},
 7: {1: <Movie id:5654088[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Dragonstone (2017)_>,
  2: <Movie id:5655178[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Stormborn (2017)_>,
  3: <Movie id:5775840[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Queen's Justice (2017)_>,
  4: <Movie id:5775846[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Spoils of War (2017)_>,
  5: <Movie id:5775854[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Eastwatch (2017)_>,
  6: <Movie id:5775864[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Beyond the Wall (2017)_>,
  7: <Movie id:5775874[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Dragon and the Wolf (2017)_>},
 8: {1: <Movie id:5924366[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" Winterfell (2019)_>,
  2: <Movie id:6027908[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" A Knight of the Seven Kingdoms (2019)_>,
  3: <Movie id:6027912[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Long Night (2019)_>,
  4: <Movie id:6027914[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Last of the Starks (2019)_>,
  5: <Movie id:6027916[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Bells (2019)_>,
  6: <Movie id:6027920[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" The Iron Throne (2019)_>}}

In [8]:
seasons = seasons_info.keys()
seasons

dict_keys([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
seasons_info[1][3].data

{'title': 'Lord Snow',
 'kind': 'episode',
 'episode of': <Movie id:0944947[http] title:_"Game of Thrones (TV Series 2011–2019) - IMDb" (None)_>,
 'season': 1,
 'episode': 3,
 'rating': 8.501234567891,
 'votes': 35708,
 'original air date': '1 May 2011',
 'year': '2011',
 'plot': "\nJon begins his training with the Night's Watch; Ned confronts his past and future at King's Landing; Daenerys finds herself at odds with Viserys.    "}

## Step 3: Create DataFrame from episodes data

### Collect episode data

In [10]:
import pandas as pd

In [11]:
ep_data = []

for season in seasons_info.values():
    for episode in season.values():
        data = episode.data
        if 'episode of' in data.keys():
            data.pop('episode of')
        df_temp = pd.DataFrame.from_records([data])
        ep_data.append(df_temp)

df = pd.concat(ep_data)  
df

,title,kind,season,episode,rating,votes,original air date,year,plot
0,Winter Is Coming,episode,1,1,8.901235,49865,17 Apr. 2011,2011,\nEddard Stark is torn between his family and ...
0,The Kingsroad,episode,1,2,8.601235,37728,24 Apr. 2011,2011,"\nWhile Bran recovers from his fall, Ned takes..."
0,Lord Snow,episode,1,3,8.501235,35708,1 May 2011,2011,\nJon begins his training with the Night's Wat...
0,"Cripples, Bastards, and Broken Things",episode,1,4,8.601235,33955,8 May 2011,2011,\nEddard investigates Jon Arryn's murder. Jon ...
0,The Wolf and the Lion,episode,1,5,9.001235,35295,15 May 2011,2011,\nCatelyn has captured Tyrion and plans to bri...
...,...,...,...,...,...,...,...,...,...
0,A Knight of the Seven Kingdoms,episode,8,2,7.901235,131945,21 Apr. 2019,2019,\nJaime faces judgment and Winterfell prepares...
0,The Long Night,episode,8,3,7.501235,217621,28 Apr. 2019,2019,\nThe Night King and his army have arrived at ...
0,The Last of the Starks,episode,8,4,5.501235,166203,5 May 2019,2019,\nThe Battle of Winterfell is over and a new c...
0,The Bells,episode,8,5,6.001235,193828,12 May 2019,2019,\nForces have arrived at King's Landing for th...
0,The Iron Throne,episode,8,6,4.001235,250885,19 May 2019,2019,\nIn the aftermath of the devastating attack o...

## Step 4: Transform DataFrame

In [12]:
rating_df = pd.pivot_table(df, index='episode', columns='season', values='rating')
rating_df

season,1,2,3,4,5,6,7,8
episode,,,,,,,,
1,8.901235,8.601235,8.601235,9.001235,8.301235,8.401235,8.501235,7.601235
2,8.601235,8.401235,8.501235,9.701235,8.301235,9.301235,8.801235,7.901235
3,8.501235,8.701235,8.701235,8.701235,8.401235,8.601235,9.101235,7.501235
4,8.601235,8.601235,9.501235,8.701235,8.501235,9.001235,9.701235,5.501235
5,9.001235,8.601235,8.901235,8.601235,8.501235,9.701235,8.701235,6.001235
6,9.101235,8.901235,8.701235,9.701235,7.901235,8.301235,9.001235,4.001235
7,9.101235,8.801235,8.601235,9.001235,8.801235,8.501235,9.401235,NaN
8,8.901235,8.601235,8.901235,9.701235,9.801235,8.301235,NaN,NaN
9,9.601235,9.601235,9.901235,9.601235,9.401235,9.901235,NaN,NaN
10,9.401235,9.301235,9.001235,9.601235,9.101235,9.901235,NaN,NaN

In [13]:
rating_df.round(1)

season     1    2    3    4    5    6    7    8
episode
1        8.9  8.6  8.6  9.0  8.3  8.4  8.5  7.6
2        8.6  8.4  8.5  9.7  8.3  9.3  8.8  7.9
3        8.5  8.7  8.7  8.7  8.4  8.6  9.1  7.5
4        8.6  8.6  9.5  8.7  8.5  9.0  9.7  5.5
5        9.0  8.6  8.9  8.6  8.5  9.7  8.7  6.0
6        9.1  8.9  8.7  9.7  7.9  8.3  9.0  4.0
7        9.1  8.8  8.6  9.0  8.8  8.5  9.4  NaN
8        8.9  8.6  8.9  9.7  9.8  8.3  NaN  NaN
9        9.6  9.6  9.9  9.6  9.4  9.9  NaN  NaN
10       9.4  9.3  9.0  9.6  9.1  9.9  NaN  NaN

In [14]:
rating_df.round(1).style.background_gradient(cmap='GnBu')

In [15]:
rating_df.round(1).fillna('')

season     1    2    3    4    5    6    7    8
episode
1        8.9  8.6  8.6  9.0  8.3  8.4  8.5  7.6
2        8.6  8.4  8.5  9.7  8.3  9.3  8.8  7.9
3        8.5  8.7  8.7  8.7  8.4  8.6  9.1  7.5
4        8.6  8.6  9.5  8.7  8.5  9.0  9.7  5.5
5        9.0  8.6  8.9  8.6  8.5  9.7  8.7  6.0
6        9.1  8.9  8.7  9.7  7.9  8.3  9.0  4.0
7        9.1  8.8  8.6  9.0  8.8  8.5  9.4
8        8.9  8.6  8.9  9.7  9.8  8.3
9        9.6  9.6  9.9  9.6  9.4  9.9
10       9.4  9.3  9.0  9.6  9.1  9.9

## Step 5: Styling for the table

In [16]:
rating_df.columns

Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64', name='season')

In [17]:
rating_df.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64', name='episode')

In [18]:
rating_df.columns.name = None               #remove categories
rating_df.index.name = None
rating_df

,1,2,3,4,5,6,7,8
1,8.901235,8.601235,8.601235,9.001235,8.301235,8.401235,8.501235,7.601235
2,8.601235,8.401235,8.501235,9.701235,8.301235,9.301235,8.801235,7.901235
3,8.501235,8.701235,8.701235,8.701235,8.401235,8.601235,9.101235,7.501235
4,8.601235,8.601235,9.501235,8.701235,8.501235,9.001235,9.701235,5.501235
5,9.001235,8.601235,8.901235,8.601235,8.501235,9.701235,8.701235,6.001235
6,9.101235,8.901235,8.701235,9.701235,7.901235,8.301235,9.001235,4.001235
7,9.101235,8.801235,8.601235,9.001235,8.801235,8.501235,9.401235,NaN
8,8.901235,8.601235,8.901235,9.701235,9.801235,8.301235,NaN,NaN
9,9.601235,9.601235,9.901235,9.601235,9.401235,9.901235,NaN,NaN
10,9.401235,9.301235,9.001235,9.601235,9.101235,9.901235,NaN,NaN

In [19]:
rating_df = rating_df.rename(columns=lambda x: 'S' + str(x))
rating_df = rating_df.rename(index=lambda x: 'Episode ' + str(x))
rating_df

,S1,S2,S3,S4,S5,S6,S7,S8
Episode 1,8.901235,8.601235,8.601235,9.001235,8.301235,8.401235,8.501235,7.601235
Episode 2,8.601235,8.401235,8.501235,9.701235,8.301235,9.301235,8.801235,7.901235
Episode 3,8.501235,8.701235,8.701235,8.701235,8.401235,8.601235,9.101235,7.501235
Episode 4,8.601235,8.601235,9.501235,8.701235,8.501235,9.001235,9.701235,5.501235
Episode 5,9.001235,8.601235,8.901235,8.601235,8.501235,9.701235,8.701235,6.001235
Episode 6,9.101235,8.901235,8.701235,9.701235,7.901235,8.301235,9.001235,4.001235
Episode 7,9.101235,8.801235,8.601235,9.001235,8.801235,8.501235,9.401235,NaN
Episode 8,8.901235,8.601235,8.901235,9.701235,9.801235,8.301235,NaN,NaN
Episode 9,9.601235,9.601235,9.901235,9.601235,9.401235,9.901235,NaN,NaN
Episode 10,9.401235,9.301235,9.001235,9.601235,9.101235,9.901235,NaN,NaN

In [20]:
rating_df.style.background_gradient(cmap='gist_heat_r', axis=None).format( precision=1, na_rep='')

### Color palletes available for matplotlib

<img src="https://i.stack.imgur.com/cmk1J.png" alt="Overview of all colormaps">